### ISSUE TITLE
100% website test via internet.nl

### ISSUE THREAD

**Issue by sgort** [MinBZK/regels.overheid.nl#10]
In GitLab by @datafluisteraar on Apr 25, 2022, 10:57

### What is Internet.nl?
[Internet.nl](https://internet.nl/) helps you to check whether your internet is up to date. Do your website, email and internet connection use modern and reliable Internet Standards? And if they don't, what can you do about it?
Who is behind Internet.nl?

The test tool Internet.nl is an initiative of the Dutch Internet Standards Platform. The aim of the platform is to jointly increase the use of modern Internet standards to make the Internet more accessible, safer and more reliable for everyone. The platform is a collaboration between parties from the Internet community and the Dutch government.

- [x] 100% website test voor regels.overheid.nl

**Comment by sgort** [comment]
To do:
- [ ] Check activeren en resultaat log opnemen zodra domein geregistreerd én live

**Comment by onursagir** [comment]
Subtasks
- [ ] #108
