### ISSUE TITLE
Fix issues related to Docker images

### ISSUE THREAD

**Issue by onursagir** [MinBZK/regels.overheid.nl#111]
"Caused" by #90

Tasks

- [ ] Image upload issue in the CMS caused by the Docker container not having the right rights to write files to a mounted volume
- [ ] Make Docker files agnostic, currently the (some) production docker files are dependent on a [Doppler](https://www.doppler.com/) token, this should not be the case. To clarify they should still be compatible with Doppler but also should work with other environment  variable related solutions.
- [ ] Unification and optimisation of Docker file, verify efficiency of Docker files and attempt a simplification and/or unification of the Docker files.

**Comment by idan279** [comment]
To clarify, unification here refers to the .dev and .prod variants, each service will still have its own Dockerfile
