### ISSUE TITLE
Align Methoden page with huisstijl as started with Home

### ISSUE THREAD

**Issue by sgort** [MinBZK/regels.overheid.nl#117]
please align Methods page with huisstijl as started with Home for:
- [x] font
- [x] font weigth/size
- [x] font color
- [x] line spacing
- [x] button(s)
- [ ] icon(s)

Other requirements:
- [x] provide scalable visualization
- [x] short explanation with limited number of words
- [x] provide applicable maximum number of words
- [x] create a button or other visual link to the relevant method page in the docusaurus

Nice to have:
- [ ] the page can show a minimum of 20 methods scalable

**Comment by sgort** [comment]
Links docusaurus:
- ALEF https://regels.overheid.nl/docs/methods/ALEF
- FLINT https://regels.overheid.nl/docs/methods/FLINT

**Comment by onursagir** [comment]
- [ ] Extend methods content-type with a link attribute so that the links mentioned above can be supplied to it

**Comment by sgort** [comment]
Please check the original [PR](https://github.com/MinBZK/regels.overheid.nl/pull/71) with demo page provided by @Robbert via Work in Progress MinBZK Design System...

![image](https://user-images.githubusercontent.com/25812095/210841349-62c6fc01-1126-4da3-baeb-9c347b8875ca.png)
