### ISSUE TITLE
Docusaurus not using Rijksoverheid Sans font

### ISSUE THREAD

**Issue by sgort** [MinBZK/regels.overheid.nl#118]
Please add Rijksoverheid Sans Web font to CSS docusaurus.

**Comment by Abinashbunty** [comment]
@sgort I checked that the Sans Web Font can be obtained from [here](https://www.rijkshuisstijl.nl/basiselementen/basiselementen-online/webfonts). But it requires access to download the font. Is it possible to request access?

**Comment by sgort** [comment]
@Abinashbunty see DM in Slack
