### ISSUE TITLE
Create Helm Repository

### ISSUE THREAD

**Issue by idan279** [MinBZK/regels.overheid.nl#121]
Split from #108

Action items:

1. Create a helm repository in the `/charts` directory
2. Integrate with the Chart Releaser Action or a similar automation
3. Create charts (Either one for the entire project, or one per service

**Comment by sgort** [comment]
I'll do that. Give me a moment.

**Comment by sgort** [comment]
Done. Consider invite sent. https://github.com/MinBZK/helm.regels.overheid.nl

**Comment by idan279** [comment]
Completed
