### ISSUE TITLE
internet.nl compliance

### ISSUE THREAD

**Issue by idan279** [MinBZK/regels.overheid.nl#126]
Split from #90 

Action items:

1. Receive 100% score on internet.nl

Tests to solve:
- TLS -> Ciphers (Trivial)
- Web Server -> IPv6 reachability of web server - **Will break on the move to Kubernetes** due to DigitalOcean's [IPv6 Limits](https://docs.digitalocean.com/products/networking/ipv6/details/limits/) and the use of load balancers instead of droplets. Can be solved by setting up a reverse proxy on a droplet and pointing it at the load balancer, but this will mean that this load balancer will need to be configured and maintained separately from the cluster. It also means that the SSL termination point will be the droplet rather than the cluster.
- TLS -> OCSP Stapling (Need to further investigate how to enable properly in the NGINX ingress controller)
- Certificate -> Trust chain of certificate (Should be trivial, pending production deployment)
- HTTP -> HSTS (Trivial)
- HTTP -> HTTP Compression (Need to further investigate how to disable properly in the NGINX ingress controller)

**HTTP security headers**

- X-Frame-Options (Trivial, set to `SAMEORIGIN` on ingress)
- X-Content-Type-Options (Trivial, set to `nosniff` on the ingress)
- Referrer-Policy (Trivial, set to `strict-origin-when-cross-origin` on the ingrs
- Content-Security-Policy (Trivial from a devops perspective **HOWEVER** things did break in the next JS project - the browser complained on inline style usage. @onursagir)
- Security.txt (Trivial, create under the `web` project)

Out of my reach:
- DANE -> DANE existence (Sort this with your registrar by adding a [TLSA](https://en.wikipedia.org/wiki/DNS-based_Authentication_of_Named_Entities) record)
- RPKI name server related tests -> Needs to be addressed with your domain registrar to see if they can do something about this.

**Comment by sgort** [comment]
@onursagir @idan279 please determine together whether this can now be closed or whether there are still open items...

![image](https://user-images.githubusercontent.com/25812095/213382902-29f62a58-2946-49ec-ada5-e8d246a54ff6.png)

**Comment by onursagir** [comment]
@sgort 3 little tasks remain

- [ ] TLS Ciphers
- [ ] HTTPS Compression
- [ ] The security.txt file a new issue has been made for this one #132

**Comment by idan279** [comment]
The compression is a false positive, it is caused by nextjs and should be sorted there;
https://nextjs.org/docs/api-reference/next.config.js/compression

I've fixed TLS ciphers, passing to @onursagir

**Comment by idan279** [comment]
`Content-Security-Policy-Report-Only` was added instead of the real counterpart, due to compatibility issues with the main project. The header is already set, it should be changed accordingly when web is fixed.
