### ISSUE TITLE
Make DCAT application profile suitable for metadata ALEF specifications

### ISSUE THREAD

**Issue by sgort** [MinBZK/regels.overheid.nl#129]
Consider this example with ALEF described conclusively. What metadata do I need to upload these specifications into a [rule library](https://regels.dexcat.nl/) and make them findable there?

Example:
- Individuele inkomenstoeslag
  - UPL https://standaarden.overheid.nl/owms/terms/indInkToesl
  - Bron https://wetten.overheid.nl/jci1.3:c:BWBR0015703&hoofdstuk=4&paragraaf=4.1&artikel=36&z=2023-01-01&g=2023-01-01
  - Specifiek gemeente Utrecht
    - https://pki.utrecht.nl/Loket/product/0c17f7cd409dc999eb351883a138ca3d
    - https://lokaleregelgeving.overheid.nl/CVDR642743

Consider this [DCAT-AP-RONL (concept)](https://minbzk.github.io/dcat-ap-ronl/) profile as a standard specification of the aforementioned metadata.

**Comment by hayoschreijer** [comment]
Hello,

One thing that might be missing is the link with the analysis of the
specific legislation to "annotations" which led to the product and
rule-set.

I asked Mariette Lokin for a "wetsanalyse" flow description to describe
metadata for the complete flow. Then we can determine if we want to, and
how, include the analysis in here.

Met vriendelijke groeten,

Hayo Schreijer
managing director Dexes
T: 06-4637 4892
E: ***@***.***


Op ma 16 jan. 2023 om 09:16 schreef Datafluisteraar <
***@***.***>:

**Comment by hayoschreijer** [comment]
Looking at the "flow" of Legitimaat (see here: https://minbzk.github.io/LegitiMaat/): 

Picture: https://minbzk.github.io/LegitiMaat/media/processen-wetsuitvoering.png

The flow implies that the model
1) metadatamodel for Rules (DCAT-RONL) sets "regels"  as centrtal object to describe. 

2) mandatory fields for the left side of the flow are relations to "wetgeving", but there can be 3 additional relations:
- - uitvoeringsbeleid [source: PUC, own website of organization]
- - analyse [as published in analysis tools, wetsanalyse editors, etc. ]
- - werkinstructies [published in PUC or online in "handboeken"] 

- EXAMPLE: for SVB the "beleidsregels are here: https://puc.overheid.nl/svb/, the beleidsregels for "schuldsanering" is here, relation URI is https://puc.overheid.nl/svb/doc/PUC_1253_20/8/. A specific rule set can link to various uitvoeringsregels, instructies, etc. In PUC there can be a link to a sub-section of a document, like in wetten.nl 

3) there are no mandatory fields for the DONL-RONL on the right part of the flow, but the following are possible: 
-- Functional design - a pre phase before code/algoritms are created. Are normally not published, but can be available in Github repositories
-- Code / Algoritms - 

In the flow, on the right bottom, there is the eventual impact of government actions based on rules. Either from the "uitleg aan en interactie met de burger" and/or in the "besluit en brief aan de burger" there will be a link to the ruleset description in a DONL-RONL register like regels.overheid.nl. This could also be a QR-code on the letter that a citizen receives from the government. 

For the DONL-RONL it is important to determine: what is stored/described as part of the "rule set" and what can be linked to. It follows that all objects on the left side of rules in the flow need to be linked to. All objects on the right side can be part of the ruleset description on DON-RONL. 

Conclusion: 
- we need to make relations in the DONL-RONL metamodel to include links to published "uitvoeringsbeleid, analysis, uitvoeringsinstructions". We also need to stimulate that these objects are published. Most of these documents are still closed source. 
- we need to offer a "distribution class" in the DONL-RONL model to describe: 
- - functional designs / links to functional designs in a Github register [documentation]
- - algorithms / code / applications where rules are executed, published in a Github register [execution]
- - manual procedures ; mostly published internally [proces descriptions]
- Each DCAT-RONL ruleset needs an URI that can be used to link in public communication / letters. 

NOTE: DCAT-RONL never publishes the actual parameters of  rules or algorithms. No gamification is possible; it is always a further explanation of the interpretations of the legislation and policies.

**Comment by diederikd** [comment]
I assume DCAT-RONL will publish the actual parameters of rules or algorithms if the source of those parameters are legislation and policies like in the example of the IIT? (https://open-regels.nl/Parameters/parameterset%202021_Parameterset.html)

**Comment by diederikd** [comment]
Isn't it usefull to use similar metadata which is used for the legislation? Like: 
![image](https://user-images.githubusercontent.com/4041616/212667379-88fb7a42-fffb-4992-9e7b-9eeb47223e94.png)

**Comment by sgort** [comment]
> I assume DCAT-RONL will publish the actual parameters of rules or algorithms if the source of those parameters are legislation and policies like in the example of the IIT? (https://open-regels.nl/Parameters/parameterset%202021_Parameterset.html)

DCAT-AP-RONL describes the metadata with which these parameters can be published and to make them retrievable for (re)use. Zie example **parameters van de regelgroep** as a distribution here https://regels.dexcat.nl/dataset/regelgroep-uit-te-keren-individuele-inkomenstoeslag

**Comment by diederikd** [comment]
I guess if rules are the central object, I would expect that above or below these rules one might find the relations to the used and derived data elements.

**Comment by sgort** [comment]
> I guess if rules are the central object, I would expect that above or below these rules one might find the relations to the used and derived data elements, including relations to the [nederlandse taxonomie](https://www.sbr-nl.nl/werken-met-sbr/taxonomie/documentatie-nederlandse-taxonomie.)

![image](https://user-images.githubusercontent.com/25812095/213381437-06587734-03b9-40ad-aebc-f47aca829fb3.png)

**Comment by diederikd** [comment]
Thanks! fixed.
