### ISSUE TITLE
Missing security.txt

### ISSUE THREAD

**Issue by onursagir** [MinBZK/regels.overheid.nl#132]
- [x] Outline what should be in the file ([example](https://example.nl/.well-known/security.txt)) @sgort 
- [ ] Sign and upload it to the web environment

**Comment by sgort** [comment]
First version included. After setting up [OSPO](https://github.com/MinBZK/Open-Source-Program-Office), there will be an improved / more extensive version.

File: [security.txt](https://github.com/MinBZK/regels.overheid.nl/files/10478231/security.txt)
