### ISSUE TITLE
Design and develop theme 

### ISSUE THREAD

**Issue by onursagir** [MinBZK/regels.overheid.nl#137]
A Material UI theme should be designed and developed that adheres to the government identity style. The list of components below is a work in progress on its own and items on the list should not be worked on unless there is separate issue for it.

## Resources

- [Material UI themeing](https://mui.com/material-ui/customization/theming/)
- [overheid.nl](https://www.overheid.nl/)

## General theming
- [x] #138
- [x] #139
- [ ] Logo
- [x] #242

## Components
- [x] #140
- [x] #141
- [x] #143
- [x] #142
- [ ] #241
- [ ] #243
- [ ] Modals
- [ ] Photography
- [ ] Tabs & Sidebar
- [x] #260
- [x] #163
- [ ] Tags
- [ ] Badges
- [ ] Tables
- [ ] Examples of every component
- [x] #261
- [ ] Accessibility options
- [ ] Cookies

## Pages

**Comment by Henneddd** [comment]
We deviated from creating components in order, as our approach involved designing pages first and then identifying the necessary components as we proceeded. Therefore, we can consider closing this issue for the time being.
