### ISSUE TITLE
Method images only show on clear cache reload.

### ISSUE THREAD

**Issue by sgort** [MinBZK/regels.overheid.nl#146]
To reproduce:

- reload Methoden with clear cache will show the images
- navigate to Roadmap and back to Methoden will show broken images (see screensot)
- clear cache reload will show images again

![image](https://user-images.githubusercontent.com/25812095/214264190-9108bb2b-8099-44b8-93fe-63cc0ab816f6.png)

**Comment by onursagir** [comment]
resolved with #148
