### ISSUE TITLE
Make the rules available via Linked Open Data in a triple store and serve it through a SPARQL-endpoint

### ISSUE THREAD

**Issue by sgort** [MinBZK/regels.overheid.nl#153]
Make the rules available via Linked Open Data in a triple store and serve it through a SPARQL-endpoint.
If we provide a SPARQL Endpoint we allow others to query our linked data/ metadata. We can provide links to the rules set download files (dumps) or the SPARQL endpoint. Download files relieve our server from strong crawling/querying activity for people interested in bulk loading (e.g. indexing) our dataset. SPARQL endpoints allow people to select a subset of their interest through a query.

Several frameworks/ tools are available for hosting RDF data. One of them is [Sesame](http://openrdf.org/), an open source framework for storing and querying RDF data. Sesame can be installed on any appropriate server. A web interface, the OpenRDF Workbench, enables you to create a new RDF repository and upload RDF triples. Once the data is uploaded to the Sesame, users can query the dataset with SPARQL, the standard query language for linked data.

Other options to publish your data include the following platforms:
- [Swirrl](http://www.swirrl.com/publishmydata): Commercial software as a service publishing platform.
- [LOD Cloud](http://datahub.io/group/lodcloud): This group catalogs data sets that are available on the Web as Linked Data and contain data links pointing at other Linked Data sets.
- [Open Data overheid](https://data.overheid.nl/): The Dutch National Open Data platform where governmental organizations can register their open datasets.
- [City-SDK](http://citysdk.waag.org/data): A webservice offering unified and direct access to open data from government, commercial and crowd sources alike. Cities can open up their data using CitySDK.
- [Platform Linked Data Nederland](http://www.platformlinkeddata.nl/): Platform that offers organizations to publish their linked open data
- [Open data Nederland](http://opendatanederland.org/): A registry listing all the open datasets of the Netherlands on one single website.
- [CKAN](http://ckan.org/): A powerful data management system that makes data accessible by providing tools to streamline publishing, sharing, finding and using data.

Source: https://www.pldn.nl/wiki/Step_8:_Publish_the_data

> Pay attention. Not all links are up to date anymore. For recognisability, we use the text of the original source.

**Comment by hayoschreijer** [comment]
Perfect idea. Keep in mind that the performance of any SPARQL endpoint is not good enough for corporate use. At least not good enough for a "reasoner" engine that needs to pull rule-fragments from the database. We are looking at a atomic-data-database (=Linked Data store) to store rule-fragments with an index for performance. Please add "atomic data" to the list: https://docs.atomicdata.dev/. 

Furthermore: most Linked Data stores are not capable of versioning/time sensitivity needed for rule fragments. We encountered this in the wetten.nl/Lido project where triples in itself are not enough to store a time/version sensitive relation.

**Comment by sgort** [comment]
Thx @hayoschreijer ! Consider Atomic data added.
The idea arose partly as a result of this exploration for the Algoritmeregister: https://regels.overheid.nl/docs/linked-data/Algoritmeregister

**Comment by sgort** [comment]
Other options to be considered? The TNO list looks outdated.

- [Virtuoso Open-Source Edition](https://vos.openlinksw.com/owiki/wiki/VOS#How%20Do%20I%20Get%20Virtuoso%3F)
- [Apache Jena](https://jena.apache.org/)

**Comment by sgort** [comment]
Until further notice an Apache Jena Fuseki server deployed and loaded with first elaboration data dictionary Algoritmeregister.
https://api-regels.nl/fuseki/#/dataset/Algoritmeregister/query
