### ISSUE TITLE
Testen Richtlijnen voor Toegankelijkheid van Webcontent (WCAG) 2.1

### ISSUE THREAD

**Issue by sgort** [MinBZK/regels.overheid.nl#17]
In GitLab by @datafluisteraar on May 27, 2022, 09:48

De Richtlijnen voor Toegankelijkheid van Webcontent (WCAG) 2.1 bevatten een groot aantal aanbevelingen om webcontent toegankelijker te maken. Het volgen van deze richtlijnen maakt content toegankelijker voor meer mensen met functiebeperkingen, waaronder blindheid en slechtziendheid, doofheid en gehoorverlies, leerproblemen, cognitieve beperkingen, motorische beperkingen, spraakproblemen, overgevoeligheid voor licht en combinaties daarvan; maar het voorziet niet in elke gebruikersbehoefte van mensen met deze beperkingen. Deze richtlijnen zijn van toepassing op de toegankelijkheid van webcontent op computers, laptops, tablets en mobiele apparaten. Het volgen van deze richtlijnen maakt webcontent doorgaans ook beter bruikbaar voor gebruikers in het algemeen ([bron](https://www.w3.org/Translations/WCAG21-nl/)).

To do's:
- [ ] zichtbaar maken op welke wijze WCAG getest wordt
- [ ] testrapportage plek geven in release management

**Comment by sgort** [comment]
Zie https://www.a11yproject.com/

**Comment by Henneddd** [comment]
While the website is in its early stages of development, we have adhered to the WCAG guidelines when designing the components. However, it's important to note that a comprehensive accessibility testing of the website has not yet been carried out. Additionally, there are some accessibility options that have not yet been implemented.

**Comment by sgort** [comment]
Zie ook https://nldesignsystem.nl/wcag/
