### ISSUE TITLE
Generate CHANGELOG.md entry with every semantic release

### ISSUE THREAD

**Issue by sgort** [MinBZK/regels.overheid.nl#215]
We currently do not keep a changelog of content releases. The issue is to do exactly that.

Nice example: https://gitlab.com/commonground/nlx/nlx/-/blob/master/CHANGELOG.md

**Comment by Abinashbunty** [comment]
There's a plugin from `semantic-release` itself which creates a changelog file. More info about it is here: https://github.com/semantic-release/changelog

**Comment by onursagir** [comment]
[Changesets](https://github.com/changesets/changesets) could also be an option as it may offer better support for monorepos.

**Comment by onursagir** [comment]
@sgort would it be possible to add [changeset-bot](https://github.com/apps/changeset-bot) to the repo? As this would allow us to automate some parts of the changeset process.

**Comment by sgort** [comment]
> @sgort would it be possible to add [changeset-bot](https://github.com/apps/changeset-bot) to the repo? As this would allow us to automate some parts of the changeset process.

Done! https://github.com/organizations/MinBZK/settings/installations/37278197
