### ISSUE TITLE
Self hosted BegrippenXL™ platform

### ISSUE THREAD

**Issue by sgort** [MinBZK/regels.overheid.nl#231]
Publishing taxonomy for our project requires a publishing environment based on open source software.

ArchiXL provides [BegrippenXL™](https://begrippen.archixl.nl/archixl/nl/) as a service.

We prefer to have a self-hosted variant available.

**Comment by marcelkrassenburg** [comment]
Kan je daar niet [https://skosmos.org/](https://skosmos.org/) voor gebruiken?

**Comment by marcelkrassenburg** [comment]
Ik denk dat BegrippenXL ook Skosmos gebruikt. Vanuit het Gegevenswoordenboek gaan we ook naar Skosmos exporteren. Of eigenlijk gewoon in Skos publiceren. Dus als we begrippen/termen van regels direct in het GGw zetten, zijn we er al 😀

Verstuurd vanaf mijn iPhone
