### ISSUE TITLE
Navigation from homepage to `Documentatie` not working

### ISSUE THREAD

**Issue by Abinashbunty** [MinBZK/regels.overheid.nl#233]
While clicking on `Documentatie` in footer while being on the homepage or any other page, it does not open the docs. Tried on all known browsers. Even on mobile devices. It only navigates after refreshing the page.

Steps to reproduce the issue:

1. Go to https://regels.overheid.nl/
2. Click on `Documentatie` in footer.

**Comment by sgort** [comment]
I happen to find out that my localhost development shows this error when clicking `documentation` link in the footer. A reload of the page yields the desired docs page.

![image](https://user-images.githubusercontent.com/25812095/233851591-b9974e81-d523-4c15-97d5-c5e34a51da27.png)

Can be reproduced and could just be the bug that is meant in this issue.

**Comment by sgort** [comment]
I think we basically need a trailing slash at the `{ title: 'Documentatie', href: '/docs' },` [here](https://github.com/MinBZK/regels.overheid.nl/blob/de5b3f1781c1f0774ba869826f1ef322cf4f7ebd/apps/web/src/components/footer.tsx#L21)?

However, I can't figure out why that isn't showing when I add it like this `{ title: 'Documentatie', href: '/docs/' },`

**Comment by onursagir** [comment]
The logic that determines wether to use `a` or a `Link` is flawed. An `a` should be used in this case but a `Link` gets used

**Comment by Abinashbunty** [comment]
I think the `href` should point to https://regels.overheid.nl/docs instead of the relative path `/docs` or `/docs/`

**Comment by onursagir** [comment]
@Abinashbunty comment will indeed fix it, but I think the behavior of the footer links should be fixed as well so that /docs also works
