### ISSUE TITLE
Als PO wil ik dat we de design tokens filosofie van het NL Design System adopteren

### ISSUE THREAD

**Issue by sgort** [MinBZK/regels.overheid.nl#28]
In GitLab by @datafluisteraar on Aug 19, 2022, 09:40

In het [NL Design System](https://www.nldesignsystem.nl/) verzamelen we principes, handvatten, elementen, patronen en richtlijnen. Zo kan de hele Nederlandse overheid samenwerken aan een begrijpelijke, gebruiksvriendelijke én toegankelijke online dienstverlening.

### design tokens
Design tokens zijn een manier om een duidelijke naam te geven aan keuzes van het visueel ontwerp van een website of huisstijl, zodat je ontwerp als data beheerd en gedeeld kan worden.

NL Design System wil de beste componenten uit de community herbruikbaar maken voor heel de overheid. Jouw huisstijl pas je toe op een bestaande component door het te combineren met een bestand met jouw design tokens: dat noemen wij een "thema".

Kleuren, afmetingen, afstanden, tekstopmaak (enzovoorts) bepaal je op een centrale plek, zodat alle teams die data gaan gebruiken om consistent je ontwerpkeuzes terug te zien in jouw producten en diensten.
We willen een standaard dataformaat ontwikkelen voor het ontwerp van de meestgebruikte componenten, door een verzameling van duidelijke en voorspelbare namen voor design tokens te hebben. NL Design System componenten moeten deze standaard design tokens gebruiken, zodat het component herbruikbaar is voor alle verschillende thema's.

Elke organisatie maakt een eigen bestand met een "thema" voor de huisstijl, waarin uiteindelijk ontwerpkeuzes staan voor enkele honderden design tokens. Componenten uit de NL Design System community kun je dus gelijk gebruiken, je hoeft alleen maar de thema te maken!

**Comment by sgort** [comment]
@sgort neemt contact op met NL Design Systeem voor afstemming bijdrage.

**Comment by sgort** [comment]
Na bericht team NL Design System fork repo op MinBZK account. Dát is het doel voor deze sprint.

**Comment by sgort** [comment]
Keuze gemaakt om éérst snelheid te maken met UX componenten regels.overheid.nl en daarna integratie, relatie en/of anderszins mbt NL Design System nader te beschouwen.

To do's:
- [ ] for NL Design System template op github/MinBZK, actie @sgort 
- [ ] selectie UX componenten library, actie @julianklumpers 
- [ ] toepassen library in context Rijkshuisstijl
- [ ] relatie NL Design System vaststellen

**Comment by julianklumpers** [comment]
Zoals besproken in de standup (04-10-'22) - vanmiddag om 1400 een meeting met Robbert en Mehmet om af te stemmen hoe we het design-systeem kunnen toepassen in een componenten library (Mui, Ant). Denk hierbij aan kleuren, border, etc...

**Comment by Henneddd** [comment]
Our proprietary component library has expanded in recent months, as mentioned in issues #243 and #241. There are still possibilities to gradually integrate the pre-defined components from NLDS at a later stage.
