### ISSUE TITLE
Work in progress publicaties toegankelijk maken

### ISSUE THREAD

**Issue by sgort** [MinBZK/regels.overheid.nl#307]
We hebben 3 varianten [publicaties](https://regels.overheid.nl/publicaties):

1. live (legitimaat)
2. work in progress (dcat)
3. binnenkort verwacht (harmonisator en calculemus protocol)

Nu ondersteunen we alleen de 1e versie. Graag ook mogelijk maken dat de 2e versie klikbaar is. Voorbeeld dcat: https://minbzk.github.io/dcat-ap-ronl/

Uiteraard onderscheid in kleurstelling zichtbaar maken.

**Comment by Henneddd** [comment]
Ah! Het ontwerp voor deze taak is al klaar in Figma en kan direct geïmplementeerd worden.
Blijkbaar vergeten comment toe te voegen excuus!

@onursagir Kan jij deze ook nog oppakken 🥺 

https://www.figma.com/file/miuXp5zu2JNhG2t3c29KBS/Design?type=design&node-id=901%3A10216&t=EHQErsyDSKCBPmUO-1
