### ISSUE TITLE
Roadmap voorbij jaargrens mogelijk maken

### ISSUE THREAD

**Issue by sgort** [MinBZK/regels.overheid.nl#308]
Momenteel omvat de roadmap visueel én inhoudelijk precies 4 kwartalen van 1 jaar. Wat nu als we óók 2024 kwartalen zichtbaar willen maken? En what about een (schuivend) window van - steeds 4? - kwartalen?

Enfin, design hiervoor een goed voorstel voor implementatie.

**Comment by Henneddd** [comment]
https://www.figma.com/file/miuXp5zu2JNhG2t3c29KBS/Design?type=design&node-id=1333%3A11397&mode=design&t=Aoi0BAX8mapaiT0z-1

@onursagir 

Try out the Dev function in Figma, you will see components 'marked' ready for dev.
