### ISSUE TITLE
Review website consistency

### ISSUE THREAD

**Issue by sgort** [MinBZK/regels.overheid.nl#318]
Header Roadmap & Methods differs significantly from other pages. Intro text Roadmap is also different.

https://www.figma.com/file/miuXp5zu2JNhG2t3c29KBS/Design?type=design&node-id=1483%3A9244&mode=design&t=qZK7IiX82EkjcJh1-1

**Comment by Henneddd** [comment]
https://www.figma.com/file/miuXp5zu2JNhG2t3c29KBS/Design?type=design&node-id=1014%3A7474&mode=design&t=5s8YXbkbusK3oANX-1

@onursagir

**Comment by Henneddd** [comment]
Compiled a quick list of essential changes that will significantly enhance our website's consistency and clarity. These improvements aim to create a more user-friendly and enjoyable browsing experience for our visitors.

https://www.figma.com/file/miuXp5zu2JNhG2t3c29KBS/Design?type=design&node-id=1483%3A9244&mode=design&t=qZK7IiX82EkjcJh1-1
