### ISSUE TITLE
Mobile Version Design and Content Categorisation for Blog Page

### ISSUE THREAD

**Issue by Henneddd** [MinBZK/regels.overheid.nl#319]
- [x] Design Mobile Version:
@Henneddd 
Review the existing desktop version design and adapt it to ensure a seamless and visually appealing mobile experience.
Consider responsive design principles, such as layout adjustments, font sizes, and element positioning, to optimize the user experience on mobile devices.

- [x] Define Categories for Content:
@sgort 
Brainstorm and identify relevant categories that will help organize and structure the blog content effectively.
Can always add to this later in the project.

- [ ] Implement Design on Live Website:
@onursagir 
Once the mobile version design is finalized, implement it on the live website.

Acceptance Criteria:

Mobile version design implemented and tested on the live website.
Categories for content are defined and approved, providing a clear structure for organizing blog posts.
The implemented design does not introduce any functional issues or conflicts with existing website features.

**Comment by sgort** [comment]
Consider this as an illustrative example for testing purposes https://www.solidcommunity.nl/vil.html

**Comment by sgort** [comment]
Vooralsnog kun je deze categorieën hanteren:

- Voorbeeld
- Demonstratie
- Methode
- Wetsanalyse
- Uitlegbaarheid
- Bestuur
- Architectuur

**Comment by Henneddd** [comment]
The web version of the blog page has been designed with a basic layout. However, certain essential options like filtering and search functionality are currently absent. Prior to proceeding, it is necessary to prioritize the design of these features (bearing in mind the limited available content). The current mobile design is based on a responsive adaptation of the webpage.

The subsequent phases involve finalizing the web version by incorporating filter and search functions, followed by the design of the mobile version.

**Comment by GillyenneTjin** [comment]
@onursagir updated version of blog is ready for development: https://www.figma.com/file/miuXp5zu2JNhG2t3c29KBS/Design?type=design&node-id=1869-19697&mode=dev 

Feel free to reach out for any questions! :)
