### ISSUE TITLE
Design New Page for ALEF Tool on Website

### ISSUE THREAD

**Issue by Henneddd** [MinBZK/regels.overheid.nl#345]
The Belastingdienst has developed a powerful tool called ALEF (Agile Law Execution Factory) using Jetbrains MPS for developing and testing rules for flexible law enforcement. The issue focuses on clear and concise content that informs and engages visitors, encouraging them to explore the ALEF tool further to gain more understanding.

Tasks

- [x] Research and gather information about the ALEF tool, its features, and its target audience to understand the requirements and goals for the page.
- [x] Define the page's structure and layout, ensuring it aligns with the overall website design and branding guidelines.
- [x] Create wireframes or low-fidelity mockups to explore different design concepts and gather feedback from stakeholders.
- [x] Develop a visual design that complements the existing website style while highlighting the uniqueness and importance of the ALEF tool.
- [x] Incorporate relevant content, such as an overview of the tool, its benefits, key features, and any necessary instructions or guidelines for usage.
- [x] Ensure the page is responsive and optimized for various devices, providing a seamless experience across desktop and mobile platforms.
- [ ] Iterate on the design based on feedback and usability testing to refine and improve the user experience.

**Comment by Henneddd** [comment]
#68

**Comment by dslmeinte** [comment]
Is ALEF open source already? ;)

A couple of links:

- https://wendbarewetsuitvoering.pleio.nl/cms/view/bae34445-59ce-4873-8f93-b832942c1b4c/alef
- https://resources.jetbrains.com/storage/products/mps/docs/MPS_DTO_Case_Study.pdf
- https://staf2019.win.tue.nl/wp-content/uploads/2019/09/STAF-ID-Adema.pdf
- https://werken.belastingdienst.nl/nieuws-en-artikelen/software-maken-met-een-fabriek-115
- https://www.werkenvoornederland.nl/organisaties/belastingdienst/nieuwe-geautomatiseerde-software-bouwen
- https://gitlab.com/commonground/virtueel-inkomstenloket/regelbeheer (@sgort knows about this one already ;))

**Comment by Henneddd** [comment]
Thank you! This is an excellent starting point. I'll definitely take the time to read it thoroughly and gain a better understanding.

**Comment by dslmeinte** [comment]
@Henneddd I worked on ALEF from ca. 2018 to 2021, and I'm happy to share any info I can.
