### ISSUE TITLE
Scaling methoden pagina gaat fout

### ISSUE THREAD

**Issue by sgort** [MinBZK/regels.overheid.nl#375]
Zie  de 'Lees meer' button verdwijnen.

Check this out bij normal zoom (ie 100%):

![image](https://github.com/MinBZK/regels.overheid.nl/assets/25812095/1f97b96a-738d-4f2c-bf7a-4f8e858e76c7)

Hier een voorbeeld bij 110% zoom:

![image](https://github.com/MinBZK/regels.overheid.nl/assets/25812095/447309ae-f2a3-4bbe-9fd9-0f296ffab83b)

**Comment by Henneddd** [comment]
I see.

The primary objective of the content should be a concise explanation, given that the exclusive intent of the call-to-action is to attract the user's interest in reading more (Lees Meer). 

Thus, the question arises: at what point should we restrict the length of the text? 
Perhaps we could discuss this matter during our Thursday meeting at the office. 
@sgort @onursagir

**Comment by onursagir** [comment]
I have made a fix in #376 that restricts the text to 7 lines for now otherwise the button it self is not visible
