### ISSUE TITLE
Registry

### ISSUE THREAD

**Issue by sgort** [MinBZK/regels.overheid.nl#4]
In GitLab by @datafluisteraar on Apr 14, 2022, 14:57

> in the original quotation this subject is part of work package 4 (WP4)

The development of the registry, the “rule bank”, including the read-in routines (consumers) of rule sources.

The code of https://data.overheid.nl, which largely includes this functionality, might be a good starting point for this.

**Comment by hayoschreijer** [comment]
Eerste versie van een register gebaseerd op de GDC software is geïmplementeerd als pilot op https://regels.dexcat.nl/. De omgeving is nog gericht op "datasets". Deze versie van de catalogus dient om uit te vinden: 
- Wat is het metadatamodel om "regels" op te nemen in een register. 
- Wat is de GAP met het datamodel voor datasets en de DCAT-AP-DONL 
- Is het nodig om een DCAT klasse voor "regels" te maken in de DCAT-AP. 

Eerste vervolg-acties zijn nu : 
- toevoegen van een aantal regels in het register en ervaring (gaps) vastleggen.

**Comment by hayoschreijer** [comment]
In het register zijn 4  regel-eigenaren aangemaakt. Er kunnen meer organisaties worden toegevoegd. De eerste regels ga ik vanaf https://commonground.gitlab.io/virtueel-inkomstenloket/regels/ halen om als voorbeeld te dienen voor een "item" in he t register.

**Comment by sgort** [comment]
De goede link voor de regels is: https://open-regels.nl/methoden/ALEF/

**Comment by sgort** [comment]
In afwachting van beheer account.
