### ISSUE TITLE
Voeg Forum functionaliteit toe mbv Discourse

### ISSUE THREAD

**Issue by sgort** [MinBZK/regels.overheid.nl#429]
Zie https://forum.developer.overheid.nl/ ter inspiratie.

Basis is [Discourse](https://github.com/discourse/discourse).

## [Install Discourse in production with the official, supported instructions](https://meta.discourse.org/t/install-discourse-in-production-with-the-official-supported-instructions/142537)
If you want to install Discourse the official, supported way, have a look at the [install Discourse document on Github 5.4k](https://github.com/discourse/discourse/blob/master/docs/INSTALL-cloud.md). If you install Discourse any other way, you’re likely to have trouble, and if you do, you’ll be less likely to get any help here.

This guide covers the official guide to install Discourse which can be used on your bare metal hosting or the cloud. If you have issues with your installation, feel free to start a topic over at our [#installation](https://meta.discourse.org/c/installation/31) support category, and someone from the community will help.

**Comment by hugoboos** [comment]
Bij Developer Overheid gebruiken we https://gitlab.com/commonground/don/forum/discourse-deploy om Discourse te deploy'en op Kubernetes.

**Comment by sgort** [comment]
forum.regels.overheid.nl & certificaat besteld

![image](https://github.com/MinBZK/regels.overheid.nl/assets/25812095/7f97f3c2-2d0e-4472-8efd-7828e09d1514)

**Comment by sgort** [comment]
Please check SSL
![image](https://github.com/MinBZK/regels.overheid.nl/assets/25812095/d67aa13a-0a91-4e63-b548-f8f00af97997)
