### ISSUE TITLE
Proposal design of forum.regels.overheid.nl using Discourse

### ISSUE THREAD

**Issue by Henneddd** [MinBZK/regels.overheid.nl#450]
Create a design for the forum based off Discourse
Example: https://forum.developer.overheid.nl

**User Interface (UI) Design:** 
Design a contemporary and user-friendly UI for forum.regels.overheid.nl, incorporating our own style while considering the distinctive needs of a government forum.

**Feature Integration:** 
Identify and integrate relevant features from Discourse that align with the forum's purpose and user expectations.

We will be using Figma.

**Comment by Henneddd** [comment]
Proposal: https://www.figma.com/file/miuXp5zu2JNhG2t3c29KBS/Design?type=design&node-id=2743%3A22429&mode=design&t=NG866concVu9ltdf-1

@sgort Please review the design and share your feedback.

The design adheres to the Discourse framework and incorporates the style of regels.overheid.nl through color adjustments.

**Comment by sgort** [comment]
@Henneddd excuus man. Dit is even aan mij ontschoten. Gezien en enthousiast. Implementeren maar! Bespreek jij het alvast met @onursagir ?
