### ISSUE TITLE
Navigatie patroon methode - docs - lab - specificaties

### ISSUE THREAD

**Issue by sgort** [MinBZK/regels.overheid.nl#461]
Bij regelspecificatie sets die we (uiteindelijk) publiceren zijn de volgende elementen veelal aanwezig op regels.overheid.nl (hier voor FLINT):

- methode https://regels.overheid.nl/methoden
- docs https://regels.overheid.nl/docs/methods/flint/INTRODUCTIE
- lab - Norm Editor https://regels.overheid.nl/lab/interpretation-editor/
- specificaties - https://regels.dexcat.nl/dataset/individuele-inkomenstoeslag-flint-regelset

Design een navigatiepartroon dat gebruikers inzicht biedt op deze beschikare elementen én die herkenbaar is, los van waar die navigatie start

**Comment by sgort** [comment]
Zie ook 
![20240404_125825](https://github.com/MinBZK/regels.overheid.nl/assets/25812095/3f05a092-3fe0-4837-953e-7af0e44059d3)

**Comment by sgort** [comment]
Notie: ook blog (voorbeeld Blueriq) in scope.

**Comment by Henneddd** [comment]
@onursagir 

Update the design of Methode, Docs & Lab
Please check the #prototype in Figma
