### ISSUE TITLE
Als PO wil ik een visualisatie waarin functionele decompositie geïllustreerd

### ISSUE THREAD

**Issue by sgort** [MinBZK/regels.overheid.nl#475]
Platform regels.overheid.nl omvat inmiddels:
- statische content
- methoden overzicht
- blogs
- respec publicaties
- lab items
- documentatie
- roadmap
- docs voor gebruikerstesten / design prototype
- agenda (wip)
- forum (wip)
- regelspecificatie sets (wip register)

Ik wil één of meerdere visualisatie(s) die voornoemde functionaliteiten in onderlinge relatie (zie in dat verband ook #461) zichtbaar helpen maken en die bruikbaar zijn in (powerpoint) presentaties.

**PS**
Wellicht is het een idee om een template pptx te maken voor regels.overheid.nl?!

**Comment by Henneddd** [comment]
Update 
Need feedback

@sgort 
[Uploading Concept Decompositie.pdf…]()

**Comment by Henneddd** [comment]
Update 
Need feedback

@sgort 
[Concept Decompositie.pdf](https://github.com/user-attachments/files/16710557/Concept.Decompositie.pdf)
