### ISSUE TITLE
Maak een regels design for AOW leeftijd demo page

### ISSUE THREAD

**Issue by sgort** [MinBZK/regels.overheid.nl#481]
Op dit moment host & deployed Belastingdienst een demo voor de AOW leeftijd service die wij deployed hebben op https://regels.overheid.nl/lab/aow-leeftijd/resultaat

Maak een design voor deze pagina in de stijl van regels.overheid.nl die geschikt is om:
- [x] te delen met Belastingdienst voor laagdrempelige deploy op de eigen omgeving
- [x] op termijn te deployen als demonstratie via de Lab pagina van regels.overheid.nl

![image](https://github.com/MinBZK/regels.overheid.nl/assets/25812095/0ede1263-44f9-4dc1-958c-91ba9d8a6f48)

**Comment by Henneddd** [comment]
Concept design:

https://www.figma.com/proto/miuXp5zu2JNhG2t3c29KBS/Design?page-id=2610%3A25487&type=design&node-id=2610-25489&viewport=824%2C643%2C0.19&t=AhQlTabRqXt1cJRR-1&scaling=min-zoom&mode=design
