### ISSUE TITLE
Deploy Legal Annotation Tool - HvA team JSON

### ISSUE THREAD

**Issue by sgort** [MinBZK/regels.overheid.nl#513]
Consists of 2 repo's:
- https://github.com/MinBZK/HvA-legal-annotation-tool-backend-json
- https://github.com/MinBZK/HvA-legal-annotation-tool-frontend-json

**Comment by sgort** [comment]
Ik krijg deze fout er niet uit bij mijn poging de applicatie op localhost aan de praat te krijgen (ie dit is de backend kant)

![image](https://github.com/MinBZK/regels.overheid.nl/assets/25812095/4266005e-1cd2-4fdd-878d-48c955af4dd4)

**Comment by onursagir** [comment]
@sgort had je `cp .env.example .env` gedaan?

**Comment by sgort** [comment]
@onursagir yep. Hij staat zelfs nog default in mijn studio als ik die folder weer open...
![image](https://github.com/MinBZK/regels.overheid.nl/assets/25812095/fae6ef6e-eb31-4f31-b993-54cae681b08b)
