### ISSUE TITLE
ReSpec pdf url not correct

### ISSUE THREAD

**Issue by sgort** [MinBZK/regels.overheid.nl#538]
`config.js` van de ReSpec publicaties produceert de link naar de [pdf](https://regels.overheid.nl/publicaties/Wetsanalyse.pdf )

```
(...)
// Create PDF and link to file in header (optional):
  alternateFormats: [
    {
        label: "pdf",
        uri: "Wetsanalyse.pdf",
    },
  ],
```
![image](https://github.com/MinBZK/regels.overheid.nl/assets/25812095/11ac2348-cc29-42f4-88eb-223a6d12af48)
Die link levert ná publicatie een 404 op. Daar moeten we iets op verzinnen.

**Comment by sgort** [comment]
Nog aan te passen de link in de html pagina. Voorbeelden:

- https://regels.overheid.nl/publicaties/Wetsanalyse.pdf moet worden https://regels.overheid.nl/publicaties/wetsanalyse/pdf
- https://regels.overheid.nl/publicaties/Algoritmeregister-Publicatiestandaard.pdf moet worden https://regels.overheid.nl/publicaties/algoritmeregister-publicatiestandaard/pdf

Let op de hoofdlettergevoeligheden...

**Comment by onursagir** [comment]
Het volgende heb ik getest en het werkt, nadat de configuraties zijn gewijzigd zal wel opnieuw een release gedaan moeten worden.
```
  alternateFormats: [
    {
        label: "pdf",
        uri: "https://regels.overheid.nl/publicaties/wetsanalyse/pdf",
    },
  ],
```
