### ISSUE TITLE
ReSpec koppeling publicatieserver

### ISSUE THREAD

**Issue by sgort** [MinBZK/regels.overheid.nl#54]
Op dit moment publiceren we de formele versie van [De LegitiMaat](https://minbzk.github.io/LegitiMaat/) naar https://open-regels.nl/lm/delegitimaat/1.0.0/ (ie straks [regels.overheid.nl](https://github.com/MinBZK/regels.overheid.nl)) door deze met de hand te kopieren. Dat kan anders.

Zie [comment Logius-standaarden/respec/issues/20](https://github.com/Logius-standaarden/respec/issues/20#issuecomment-1239192772) voor nadere info.

**Comment by sgort** [comment]
Waar het om gaat is dat we een manier vinden om de [snapshot](https://github.com/MinBZK/LegitiMaat/blob/main/snapshot.html) van bijv. De LegitiMaat te kunnen publiceren op regels.overheid.nl, zonder menselijke tussenkomst ná generatie van die snapshot.

**Comment by onursagir** [comment]
- [ ] Create an endpoint that will download release from a GitHub repo and store them on the server. 
- [ ] Create a workflow file that repo's can use to call an endpoint on regels.overheid.nl to trigger a publication
- [ ] Create an endpoint to list publications that are on the server
