### ISSUE TITLE
Website Analytics

### ISSUE THREAD

**Issue by sgort** [MinBZK/regels.overheid.nl#56]
Voor open-regels.nl gebruik ik Google Analytics met mijn eigen, persoonlijke account (zie hieronder). Hieromtrent voor regels.overheid.nl (nog) een keuze te maken. Zelf ben ik wel gecharmeerd van https://www.offen.dev/

![image](https://user-images.githubusercontent.com/25812095/189104246-4a3d1c6e-8e42-4297-9659-533a8130dea7.png)

**Comment by onursagir** [comment]
- [ ] Self host Offen Fair Web Analytics while protecting your users' data.
- [ ] Integrate the code snippet into pages you want to track.

**Comment by onursagir** [comment]
Related: [offen #769](https://github.com/offen/offen/issues/769)
