### ISSUE TITLE
Storing secrets

### ISSUE THREAD

**Issue by sgort** [MinBZK/regels.overheid.nl#58]
What options or combinations of these are there for the proper storage of the secrets that our application needs?

## options
- external config files
- environmental variables
- a key vault (ie https://www.vaultproject.io/)
- managed identities (ie have the underlying infrastructure or platform manage the access control)

**Comment by onursagir** [comment]
I think we first need to decide how we classify environment variables vs secrets:
- The location of our public API? _Probably_ an environment variable
- The credentials of our database? Definitely a secret

These secrets would need to be stored in Github under the secrets sections in this repository as the Github actions will need access to them. As for sharing the secrets/environment variables we could also take a look into [1Password for teams](https://1password.com/teams/?utm_source=google&utm_medium=cpc&utm_campaign=16264614230&utm_content=582668427342&utm_term=teams%201password&gclsrc=ds) (or any other password manager) which we could also use for sharing passwords. We should also keep in mind that if we go with a vault/password manager somebody would need to be tasked with the responsibility of granting and revoking access to team members
