### ISSUE TITLE
Bronverwijzing blog artikelen toevoegen waar relevant

### ISSUE THREAD

**Issue by sgort** [MinBZK/regels.overheid.nl#590]
voorbeeld https://regels.overheid.nl/blog/11/van-wet-en-regelgeving-naar-regelservice met bron https://www.blueriq.com/actueel/van-wet-en-regelgeving-naar-regelservice

**Comment by Henneddd** [comment]
@onursagir 

Toevoeging aan de blogpagina: https://www.figma.com/proto/miuXp5zu2JNhG2t3c29KBS/Design?page-id=74%3A712&node-id=4225-16414&node-type=canvas&viewport=-44716%2C-5681%2C0.67&t=6DNR9CIzScvL3SLj-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=2169%3A12846

We gebruiken de component [Label] te vinden in Figma en de bronvermelding dient te gebeuren in APA-stijl.

**Comment by sgort** [comment]
Solved bij #620
