### ISSUE TITLE
Update naming on the buttons "Parameter raadplegen etc" 

### ISSUE THREAD

**Issue by Henneddd** [MinBZK/regels.overheid.nl#598]
@onursagir 
Please update all the buttons on this page to:

"Service raadplegen"
"Regelgroep raadplegen" 
""
etc

https://regels.overheid.nl/register/indInkToesl

**Comment by sgort** [comment]
Inclusief fix rendering HTML.

**Comment by sgort** [comment]
Apart from rendering HTML, page will be fine after #612
