### ISSUE TITLE
Design issue method pagina (en wellicht meer)

### ISSUE THREAD

**Issue by sgort** [MinBZK/regels.overheid.nl#625]
Bij klein(er) window valt de tekst 'uit' de card waardoor design 'breekt'. Zie voorbeeld.
![image](https://github.com/user-attachments/assets/cdbe863c-2615-418c-b0d2-59be426b90ca)

Bij schermvullend window ziet het er zo uit.
![image](https://github.com/user-attachments/assets/f55e5687-983a-4851-a644-023034fbea7d)

**Comment by Henneddd** [comment]
Ik heb hier best mee geworsteld, maar ik ga het delen in de Nederlandse design community. Ik ga ook eens kijken hoe andere design systemen dit aanpakken. Uit mijn ervaring voelt het alsof "cards" niet echt geschikt zijn als we zoveel tekst willen gebruiken. Ze zouden meer een korte introductie moeten zijn, met een call-to-action-knop die gebruikers naar meer info stuurt.

**Comment by Henneddd** [comment]
Ah, oké! In het ontwerp gebeurt dat al, het is alleen de vraag of het in de praktijk mogelijk is.
Ik zal een call inplannen met Mehmet om de opties te verkennen.

**Comment by sgort** [comment]
Top. Doe sowieso die check bij de design community.

**Comment by Henneddd** [comment]
Ik heb de vraag aan de community voorgelegd:
Het huidige ontwerp is prima. Onze kaartteksten, dus content, zijn simpelweg te lang. Het gebruik van afkapping met drie puntjes **NIET** toegankelijk en dus niet toegestaan. We moeten de teksten inkorten. 
Het doel van de kaarten is om de interesse van de gebruiker te wekken, het liefst maximaal 1 zin.

**Comment by sgort** [comment]
Check. Ik pas waar nodig de teksten aan.
