### ISSUE TITLE
Blog visualisatie design

### ISSUE THREAD

**Issue by sgort** [MinBZK/regels.overheid.nl#630]
Graag een fraai design maken obv bijgevoegd voorbeeld (pptx enclosed)
![image](https://github.com/user-attachments/assets/754db28a-fd7b-494d-a1f8-3c33bd3c9fa5)

[InBijOver Plaat.pptx](https://github.com/user-attachments/files/17327345/InBijOver.Plaat.pptx)

**Comment by Henneddd** [comment]
![Visualisatie blog-01](https://github.com/user-attachments/assets/772e5539-fa1f-4f23-b490-19c844106555)

**Comment by Henneddd** [comment]
![New Visual](https://github.com/user-attachments/assets/f9ba9b22-ce2d-4ca3-9374-2749b84c53d7)

**Comment by Henneddd** [comment]
![New Visual](https://github.com/user-attachments/assets/bee3cf43-7a4b-4209-bfe1-40a940dae8c0)

SVG

**Comment by sgort** [comment]
graag van bijgevoegde figuren ook een fraaier exemplaar voor in de blog
![methodeplaat](https://github.com/user-attachments/assets/a9ad1db5-e45d-4fd0-823a-28c71b4c9bd8)
![bedrijfsfuncties](https://github.com/user-attachments/assets/8a793a6d-63b3-435d-88f8-401c5fe9b0d5)

**Comment by Henneddd** [comment]
![Processtroom voetnoot 4](https://github.com/user-attachments/assets/ef5a1368-09db-40e3-8287-34a65cb956af)
![Besluitvormingsproces voetnoot 2](https://github.com/user-attachments/assets/69a6cc52-7dfa-405a-bfe0-8231a76a3de0)

**Comment by Henneddd** [comment]
![Besluitvormingsproces voetnoot 2](https://github.com/user-attachments/assets/4928e1d3-ec5a-4370-9c00-f8ea9f45e852)
![Processtroom voetnoot 4](https://github.com/user-attachments/assets/a58410b1-a546-4340-a448-02cd67d772c9)
