### ISSUE TITLE
Testomgeving voor regels.overheid.nl obv tech stack GDC

### ISSUE THREAD

**Issue by sgort** [MinBZK/regels.overheid.nl#69]
- [ ] open source code base
- [ ] as a service afnemen
- [ ] demo url gebruiken voor testen

**Comment by hayoschreijer** [comment]
Voeg mij maar toe aan dit ticket.

**Comment by sgort** [comment]
Consider invite sent. Ik assign zodra je aan boord bent ;-)
![image](https://user-images.githubusercontent.com/25812095/194834640-958e0787-8585-41c5-a24f-3cf0778624ee.png)

**Comment by hayoschreijer** [comment]
IK heb de invite nog een keer geaccepteerd, hopelijk werkt het nu.
